package com.aihc.transithub.config;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Contact;
import io.swagger.v3.oas.models.info.Info;
import io.swagger.v3.oas.models.info.License;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 * OpenAPI configuration class for customizing the API documentation generated by Spring doc OpenAPI.
 * This class defines the metadata for the API, such as title, version, description, contact information,
 * and license details.
 *
 * @author Alvaro Huanca
 */
@Configuration
public class OpenApiConfig {

    @Bean
    public OpenAPI customOpenAPI() {
        return new OpenAPI()
                .info(new Info()
                        .title("TransitHub API")
                        .version("1.0.0")
                        .description("API documentation for TransitHub - Transit management system")
                        .contact(new Contact()
                                .name("TransitHub Team")
                                .email("support@transithub.com"))
                        .license(new License()
                                .name("Apache 2.0")
                                .url("https://www.apache.org/licenses/LICENSE-2.0.html")));
    }
}

